// <auto-generated />
namespace SetareSazBot.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class video_status : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(video_status));
        
        string IMigrationMetadata.Id
        {
            get { return "201901120819170_video_status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
